### basic ###
io_config: io.yaml
camnames: ['Camera1', 'Camera2', 'Camera3', 'Camera4', 'Camera5', 'Camera6']

### data ###
n_channels_in: 3
n_channels_out: 22
new_n_channels_out: 22
n_views: 6

### train ###
batch_size: 4
epochs: 1200
lr: 0.0001
train_mode: new

save_period: 5
data_split_seed: 1024

#optimizer: 

#lr_scheduler:
#  type: MultiStepLR
#  args: 
#      milestones: []

### architecture ###
custom_model:
    name: lt
    architecture: pose_resnet
    backbone_pretrained: #./comparison/poseresnet_s386_noskew_normim_sigma3/checkpoint-epoch700.pth
    
    crop_size: 600
    resize_size: 384
    
    use_gt_bbox: True
    
### loss ###
metric: ['euclidean_distance']
loss:
    L1Loss:
      loss_weight: 1.0

### augmentations ###      
medfilt_window: 30
rand_view_replace: True
n_rand_views: 6
mirror_augmentation: False
left_keypoints: [1, 7, 8, 9, 10, 15, 16, 17, 18]
right_keypoints: [2, 11, 12, 13, 14, 19, 20, 21, 22]

augment_hue: False
augment_brightness: False
augment_bright_val: 0.01

### predictions ###
max_num_samples: max


vmin: -60
vmax: 60
nvox: 64
interp: nearest

expval: True
net_type: "dannce"